[build]
  command = "cd backend && npm install && npm run build && ln -s /tmp uploads"
  publish = "backend/build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
